<a href="https://colab.research.google.com/github/anubhavgupta1/Udacity/blob/main/Frameworks/Tensorflow/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup

In [1]:
import tensorflow as tf
from tensorflow import keras

## Tensor Constants

In [2]:
X = tf.constant([[5, 2], [1, 3]])
print(X)
print("dtype:", X.dtype)
print("shape:", X.shape)

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)
dtype: <dtype: 'int32'>
shape: (2, 2)


## Tensor Constants via tf.ones and tf.zeros 

In [3]:
X = tf.ones(shape=(2, 1))
Y = tf.zeros(shape=(2, 1))
print(X)
print(Y)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


## Random Constant Tensors

In [4]:
X = tf.random.normal(shape=(2, 2), mean=0.0, stddev=1.0)
Y = tf.random.uniform(shape=(2, 2), minval=0, maxval=10, dtype="int32")
print(X)
print(Y)

tf.Tensor(
[[-0.95891917 -1.5988225 ]
 [-1.0177909   0.4417572 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2 6]
 [6 6]], shape=(2, 2), dtype=int32)


## Variables

In [5]:
initial_value = tf.random.normal(shape=(2, 2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.5189735 ,  0.762988  ],
       [ 0.22817664,  0.8628653 ]], dtype=float32)>


#### You update the value of a Variable by using the methods .assign(value),assign_add(increment), or .assign_sub(decrement):

In [6]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.7787517 ,  2.0455437 ],
       [-0.92930007, -0.22045809]], dtype=float32)>


In [7]:
added_value = tf.random.normal(shape=(2, 2))
a.assign_add(added_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-4.0213923 ,  1.3225266 ],
       [ 0.24922359, -0.49223682]], dtype=float32)>


In [8]:
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j] + added_value[i, j]
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-4.0213923 ,  1.3225266 ],
       [ 0.24922359, -0.49223682]], dtype=float32)>


## Maths in TF

In [9]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))
print(a)
print(b)

tf.Tensor(
[[-0.6332619   1.4715046 ]
 [-0.19893837 -1.3217686 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.0818979   0.9864255 ]
 [-0.62936914  0.4656114 ]], shape=(2, 2), dtype=float32)


In [10]:
c = a + b
print(c)

tf.Tensor(
[[-1.7151598   2.45793   ]
 [-0.8283075  -0.85615724]], shape=(2, 2), dtype=float32)


In [11]:
d = tf.square(c)
print(d)

tf.Tensor(
[[2.941773   6.0414205 ]
 [0.68609333 0.7330052 ]], shape=(2, 2), dtype=float32)


In [12]:
e = tf.exp(d)
print(e)

tf.Tensor(
[[ 18.949413  420.4899   ]
 [  1.9859419   2.081326 ]], shape=(2, 2), dtype=float32)


In [13]:
f = tf.sqrt(tf.square(a) + tf.square(b))
print(f)

tf.Tensor(
[[1.2536043  1.771542  ]
 [0.66006213 1.4013802 ]], shape=(2, 2), dtype=float32)


## Gradients

In [14]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

with tf.GradientTape() as tape:
    tape.watch(a)  # Start recording the history of operations applied to `a`
    c = tf.sqrt(tf.square(a) + tf.square(b))  # Do some math using `a`
    # What's the gradient of `c` with respect to `a`?
    dc_da = tape.gradient(c, a)
    print(dc_da)

tf.Tensor(
[[ 0.4628807 -0.994049 ]
 [ 0.7238441  0.6806107]], shape=(2, 2), dtype=float32)


#### By default, variables are watched automatically, so you don't need to manually watch them:

In [15]:
a = tf.Variable(a)

with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c, a)
    print(dc_da)

tf.Tensor(
[[ 0.4628807 -0.994049 ]
 [ 0.7238441  0.6806107]], shape=(2, 2), dtype=float32)


In [16]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a) + tf.square(b))
        dc_da = tape.gradient(c, a)
    d2c_da2 = outer_tape.gradient(dc_da, a)
    print(d2c_da2)

tf.Tensor(
[[0.7847075  0.02863288]
 [0.27968067 0.25622725]], shape=(2, 2), dtype=float32)
