<a href="https://colab.research.google.com/github/anubhavgupta1/Udacity/blob/main/Frameworks/Pytorch/Basics/Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup

In [1]:
import time
import torch
import numpy as np
import matplotlib.pyplot as plt

## Tensor Constants

In [2]:
X = torch.ones(3,2)
print(X)
X = torch.zeros(3,2)
print(X)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


## Intializing Tensors

In [3]:
X = torch.linspace(0,10, steps = 5)
print(X)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [4]:
X = torch.tensor([[2,3],[4,5],[7,8]])
print(X,"\n")
print(X.shape,"\n")
print(X.size(),"\n")

tensor([[2, 3],
        [4, 5],
        [7, 8]]) 

torch.Size([3, 2]) 

torch.Size([3, 2]) 



## Slicing Tensors

In [5]:
print(X[:,1],"\n")
print(X[0,:],"\n")
Y = X[1,1]
print(Y,"\n")
print(Y.item(),"\n")

tensor([3, 5, 8]) 

tensor([2, 3]) 

tensor(5) 

5 



## Reshaping Tensors

In [6]:
X = torch.linspace(0,10, steps = 50)
Y = X.reshape(2,5,5)
print(Y)

tensor([[[ 0.0000,  0.2041,  0.4082,  0.6122,  0.8163],
         [ 1.0204,  1.2245,  1.4286,  1.6327,  1.8367],
         [ 2.0408,  2.2449,  2.4490,  2.6531,  2.8571],
         [ 3.0612,  3.2653,  3.4694,  3.6735,  3.8776],
         [ 4.0816,  4.2857,  4.4898,  4.6939,  4.8980]],

        [[ 5.1020,  5.3061,  5.5102,  5.7143,  5.9184],
         [ 6.1224,  6.3265,  6.5306,  6.7347,  6.9388],
         [ 7.1429,  7.3469,  7.5510,  7.7551,  7.9592],
         [ 8.1633,  8.3673,  8.5714,  8.7755,  8.9796],
         [ 9.1837,  9.3878,  9.5918,  9.7959, 10.0000]]])


In [7]:
Y = X.view(2,5,5)
print(Y)

tensor([[[ 0.0000,  0.2041,  0.4082,  0.6122,  0.8163],
         [ 1.0204,  1.2245,  1.4286,  1.6327,  1.8367],
         [ 2.0408,  2.2449,  2.4490,  2.6531,  2.8571],
         [ 3.0612,  3.2653,  3.4694,  3.6735,  3.8776],
         [ 4.0816,  4.2857,  4.4898,  4.6939,  4.8980]],

        [[ 5.1020,  5.3061,  5.5102,  5.7143,  5.9184],
         [ 6.1224,  6.3265,  6.5306,  6.7347,  6.9388],
         [ 7.1429,  7.3469,  7.5510,  7.7551,  7.9592],
         [ 8.1633,  8.3673,  8.5714,  8.7755,  8.9796],
         [ 9.1837,  9.3878,  9.5918,  9.7959, 10.0000]]])


In [8]:
X = torch.linspace(0,10, steps = 5).view(1,5)
Y = X.view(5,-1)
print(Y)

tensor([[ 0.0000],
        [ 2.5000],
        [ 5.0000],
        [ 7.5000],
        [10.0000]])


## Torch Operations

In [9]:
X = torch.ones([3,2])
Y = torch.ones([3,2])
print(X + Y, "\n")
print(X -Y, "\n")
print(Y.add(X),"\n")
print((X+Y)*(X+Y),"\n")

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]]) 

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) 

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]]) 

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]]) 



In [10]:
print(Y.add_(X),"\n")
print(Y,"\n")

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]]) 

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]]) 



## Pytotch vs Numpy

In [11]:
X = Y.numpy()
print(type(X),"\n")

<class 'numpy.ndarray'> 



In [12]:
Y = torch.from_numpy(X)
print(type(Y),"\n")

<class 'torch.Tensor'> 



In [13]:
np.add(X,1, out=X)
print(X,"\n")
print(Y,"\n")

[[3. 3.]
 [3. 3.]
 [3. 3.]] 

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]]) 



In [14]:
%%time
for i in range(1000):
  a = np.random.randn(100,100)
  b = np.random.randn(100,100)
  c = a * b

CPU times: user 732 ms, sys: 0 ns, total: 732 ms
Wall time: 733 ms


In [15]:
%%time
for i in range(1000):
  a = torch.randn([100,100])
  b = torch.randn([100,100])
  c = a * b

CPU times: user 199 ms, sys: 0 ns, total: 199 ms
Wall time: 204 ms


In [16]:
%%time
for i in range(1000):
  a = np.random.randn(1000,1000)
  b = np.random.randn(1000,1000)
  c = a * b

CPU times: user 1min 11s, sys: 57.5 ms, total: 1min 12s
Wall time: 1min 12s


In [17]:
%%time
for i in range(1000):
  a = torch.randn([1000,1000])
  b = torch.randn([1000,1000])
  c = a * b

CPU times: user 18.6 s, sys: 35 ms, total: 18.6 s
Wall time: 18.6 s


## Cuda Support

In [18]:
print(torch.cuda.device_count())

1


In [19]:
print(torch.cuda.get_device_name(0))

Tesla T4


In [20]:
gpu = torch.device('cuda:0')

In [21]:
%%time
for i in range(1000):
  a = torch.randn([1000,1000],device=gpu)
  b = torch.randn([1000,1000],device=gpu)
  c = a * b 

CPU times: user 2.97 s, sys: 1.36 s, total: 4.33 s
Wall time: 10.2 s


In [22]:
a = torch.randn([1000,1000])
b = torch.randn([1000,1000])
c = a + b
print(c)

tensor([[ 2.3347, -0.1000, -1.3608,  ..., -1.9330, -0.3654, -2.0877],
        [ 0.5789, -0.3118,  1.8707,  ...,  1.1448, -0.1975,  0.9215],
        [-0.8124, -3.5418,  0.7857,  ..., -0.0770,  1.9254, -0.2258],
        ...,
        [-0.9009, -0.2286,  0.5621,  ..., -0.5216,  0.3700, -1.1375],
        [-0.6500, -0.1132,  0.5563,  ..., -1.5498,  0.0892,  1.0754],
        [ 2.1305, -1.5260,  1.3369,  ...,  2.0197, -2.1878,  1.1183]])


In [23]:
a = a.to(gpu)
b = b.to(gpu)
c = a + b
print(c)

tensor([[ 2.3347, -0.1000, -1.3608,  ..., -1.9330, -0.3654, -2.0877],
        [ 0.5789, -0.3118,  1.8707,  ...,  1.1448, -0.1975,  0.9215],
        [-0.8124, -3.5418,  0.7857,  ..., -0.0770,  1.9254, -0.2258],
        ...,
        [-0.9009, -0.2286,  0.5621,  ..., -0.5216,  0.3700, -1.1375],
        [-0.6500, -0.1132,  0.5563,  ..., -1.5498,  0.0892,  1.0754],
        [ 2.1305, -1.5260,  1.3369,  ...,  2.0197, -2.1878,  1.1183]],
       device='cuda:0')


In [24]:
X = torch.ones(2, 2, requires_grad=True)
print(X)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [25]:
Y = X + 2
print(Y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [26]:
Z = Y * Y * 3
print(Z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [27]:
t1 = torch.sum(Z)
print(t1)

tensor(108., grad_fn=<SumBackward0>)


In [28]:
t1.backward()
print(X.grad)

tensor([[18., 18.],
        [18., 18.]])


In [29]:
X = torch.ones(2, 2, requires_grad=True)
Y = X + 5
Z = 1 / (1 + torch.exp(-Y))
t = torch.sum(Z)
t.backward()
print(X.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025]])


In [30]:
learning_rate = 0.01

w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

print("\n=====================================\n")
for epoch in range(100):
  
  x = torch.randn([20, 1])
  y = 3*x - 2
  
  y_hat = w*x + b
  
  loss = torch.sum((y_hat - y)**2)
  loss.backward()
  if ( epoch % 10 == 9 ):
    print("Epoch is : ",epoch+1," and loss is ", loss.item())

  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
    
    w.grad.zero_()
    b.grad.zero_()
  
  if ( epoch % 10 == 9 ):
    print(w.item(), b.item())
    print("\n=====================================\n")
  



Epoch is :  10  and loss is  0.008452343754470348
2.9970810413360596 -1.9877763986587524


Epoch is :  20  and loss is  2.6303371214453364e-07
3.0000202655792236 -1.999928593635559


Epoch is :  30  and loss is  4.8260062612826005e-11
3.0000007152557373 -1.9999996423721313


Epoch is :  40  and loss is  3.0127011996228248e-12
3.0 -2.0


Epoch is :  50  and loss is  0.0
3.0 -2.0


Epoch is :  60  and loss is  0.0
3.0 -2.0


Epoch is :  70  and loss is  0.0
3.0 -2.0


Epoch is :  80  and loss is  0.0
3.0 -2.0


Epoch is :  90  and loss is  0.0
3.0 -2.0


Epoch is :  100  and loss is  0.0
3.0 -2.0


