<a href="https://colab.research.google.com/github/anubhavgupta1/Udacity/blob/main/Frameworks/Pytorch/Basics/Torch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

## `Tensor Properties`

In [2]:
example_tensor = torch.Tensor(
    [
     [[1, 2], [3, 4]], 
     [[5, 6], [7, 8]], 
     [[9, 0], [1, 2]]
    ]
)

In [3]:
print(example_tensor.shape)
print("shape[0] =", example_tensor.shape[0])
print("size(1) =", example_tensor.size(1))
print("Rank =", len(example_tensor.shape))
print("Number of elements =", example_tensor.numel())

torch.Size([3, 2, 2])
shape[0] = 3
size(1) = 2
Rank = 3
Number of elements = 12


## `Tensor Properties: Device`

In [4]:
example_tensor.device

device(type='cpu')

## `Indexing Tensors`

In [5]:
example_tensor[1]

tensor([[5., 6.],
        [7., 8.]])

In [6]:
example_tensor[1, 1, 0]

tensor(7.)

In [7]:
example_scalar = example_tensor[1, 1, 0]
example_scalar.item()

7.0

In [8]:
example_tensor[:, 0, 0]

tensor([1., 5., 9.])

## `Initializing Tensors`

In [9]:
torch.ones_like(example_tensor)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [10]:
torch.zeros_like(example_tensor)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [11]:
torch.randn_like(example_tensor)

tensor([[[ 1.3612,  0.5294],
         [ 0.5651,  0.0544]],

        [[-0.0414, -2.2910],
         [ 1.2220, -0.4478]],

        [[-0.3136,  0.3230],
         [-0.4213, -0.7926]]])

In [12]:
torch.randn(2, 2, device='cpu') # Alternatively, for a GPU tensor, you'd use device='cuda'

tensor([[ 0.2740,  1.2976],
        [ 0.5991, -0.7598]])

## `Basic Functions`

In [13]:
(example_tensor - 5) * 2

tensor([[[ -8.,  -6.],
         [ -4.,  -2.]],

        [[  0.,   2.],
         [  4.,   6.]],

        [[  8., -10.],
         [ -8.,  -6.]]])

In [14]:
print("Mean:", example_tensor.mean())
print("Stdev:", example_tensor.std())

Mean: tensor(4.)
Stdev: tensor(2.9848)


In [15]:
example_tensor.mean(0)

# Equivalently, you could also write:
# example_tensor.mean(dim=0)
# example_tensor.mean(axis=0)
# torch.mean(example_tensor, 0)
# torch.mean(example_tensor, dim=0)

tensor([[5.0000, 2.6667],
        [3.6667, 4.6667]])

## `PyTorch Neural Network Module (torch.nn)`

In [16]:
import torch.nn as nn

### `nn.linear`

In [17]:
linear = nn.Linear(10, 2)
example_input = torch.randn(3, 10)
example_output = linear(example_input)
example_output

tensor([[ 0.0704,  0.5484],
        [-0.4784,  0.4316],
        [ 0.3064,  0.2845]], grad_fn=<AddmmBackward>)

### `nn.Relu`

In [18]:
relu = nn.ReLU()
relu_output = relu(example_output)
relu_output

tensor([[0.0704, 0.5484],
        [0.0000, 0.4316],
        [0.3064, 0.2845]], grad_fn=<ReluBackward0>)

### `nn.BatchNorm1d`

In [19]:
batchnorm = nn.BatchNorm1d(2)
batchnorm_output = batchnorm(relu_output)
batchnorm_output

tensor([[-0.4213,  1.1749],
        [-0.9581,  0.0933],
        [ 1.3794, -1.2682]], grad_fn=<NativeBatchNormBackward>)

### `nn.Sequential()`

In [20]:
mlp_layer = nn.Sequential(
    nn.Linear(5, 2),
    nn.BatchNorm1d(2),
    nn.ReLU()
)

test_example = torch.randn(5,5) + 1
print("input: ")
print(test_example)
print("output: ")
print(mlp_layer(test_example))

input: 
tensor([[ 2.1720e+00,  1.3182e+00,  1.2679e+00,  1.8542e-01,  8.2240e-01],
        [ 1.6193e+00, -2.0721e-01,  2.3490e+00,  9.7968e-02,  1.1816e+00],
        [ 1.4042e+00,  1.0355e+00,  1.0615e+00, -2.1066e+00,  1.6537e+00],
        [ 2.3411e+00,  2.1448e+00,  6.7567e-01, -8.1138e-02,  9.2366e-02],
        [ 3.0776e+00,  1.7488e-04,  6.7086e-01,  4.0466e-01,  3.8216e-01]])
output: 
tensor([[0.0000, 0.1327],
        [1.4279, 1.0879],
        [0.9309, 1.0279],
        [0.0000, 0.0000],
        [0.0000, 0.0000]], grad_fn=<ReluBackward0>)


## `Optimizers`

In [21]:
import torch.optim as optim
adam_opt = optim.Adam(mlp_layer.parameters(), lr=1e-1)

## `Training loop`

In [22]:
train_example = torch.randn(100,5) + 1
adam_opt.zero_grad()

# We'll use a simple loss function of mean distance from 1
# torch.abs takes the absolute value of a tensor
cur_loss = torch.abs(1 - mlp_layer(train_example)).mean()

cur_loss.backward()
adam_opt.step()
print(cur_loss)

tensor(0.7560, grad_fn=<MeanBackward0>)


## `nn.class`

In [23]:
class ExampleModule(nn.Module):
    def __init__(self, input_dims, output_dims):
        super(ExampleModule, self).__init__()
        self.linear = nn.Linear(input_dims, output_dims)
        self.exponent = nn.Parameter(torch.tensor(1.))

    def forward(self, x):
        x = self.linear(x)

        # This is the notation for element-wise exponentiation, 
        # which matches python in general
        x = x ** self.exponent 
        
        return x

In [24]:
example_model = ExampleModule(10, 2)
list(example_model.parameters())

[Parameter containing:
 tensor(1., requires_grad=True), Parameter containing:
 tensor([[ 0.0631, -0.2466,  0.2183, -0.0528, -0.2260, -0.0105, -0.0904, -0.2834,
          -0.0645, -0.1889],
         [ 0.1647, -0.1744, -0.2623,  0.2025,  0.2671, -0.0699,  0.0691, -0.3035,
          -0.1977, -0.1243]], requires_grad=True), Parameter containing:
 tensor([ 0.2181, -0.0385], requires_grad=True)]

In [25]:
list(example_model.named_parameters())

[('exponent', Parameter containing:
  tensor(1., requires_grad=True)), ('linear.weight', Parameter containing:
  tensor([[ 0.0631, -0.2466,  0.2183, -0.0528, -0.2260, -0.0105, -0.0904, -0.2834,
           -0.0645, -0.1889],
          [ 0.1647, -0.1744, -0.2623,  0.2025,  0.2671, -0.0699,  0.0691, -0.3035,
           -0.1977, -0.1243]], requires_grad=True)), ('linear.bias',
  Parameter containing:
  tensor([ 0.2181, -0.0385], requires_grad=True))]

In [26]:
input = torch.randn(2, 10)
example_model(input)

tensor([[ 0.7044, -0.3044],
        [ 0.4572,  1.3685]], grad_fn=<PowBackward1>)