<a href="https://colab.research.google.com/github/anubhavgupta1/Udacity/blob/main/1_Matrix_Math_and_NumPy_Refresher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

#**Matrix Math and NumPy Refresher**

##**Scalors**

In [2]:
s = np.array(5)
print("np.array(5) gives us scalor : ",s)
print("The shape of scalor is : ",s.shape)

np.array(5) gives us scalor :  5
The shape of scalor is :  ()


###**Scalor Addition**

In [3]:
x = s + 3
print("s + 3 : ",x)

s + 3 :  8


##**Vectors**

In [4]:
v = np.array([1,2,3])
print("v = np.array([1,2,3]) gives us vetor v : ",v)
print("The shape of vector v is : ",v.shape)
print("v[1] returns us scalor : ",v[1])
print("Slicing the numpy vector : ",v[1:])

v = np.array([1,2,3]) gives us vetor v :  [1 2 3]
The shape of vector v is :  (3,)
v[1] returns us scalor :  2
Slicing the numpy vector :  [2 3]


##**Matrices**

In [5]:
m = np.array([v,v+3,v+6])
print("Matrix is vector of vector : \n",m)
print("The shape of matrix is : ", m.shape)
print("m[1][2] returns us scalor : ",m[1][2])

Matrix is vector of vector : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The shape of matrix is :  (3, 3)
m[1][2] returns us scalor :  6


##**Tensor**

In [6]:
t = np.array([
              [
                  [
                      [1,2],[3,4]
                  ],
                  [
                      [5,6],[7,8]
                  ]
              ],
              [
                  [
                      [9,10],[11,12]
                  ],
                  [
                      [13,14],[15,16]
                  ]
              ]
])

In [7]:
t.shape

(2, 2, 2, 2)

##**Changing the shapes**

In [8]:
v = np.array([1,2,3,4])
x = v.reshape(1,4)
print("The shape of vector v is ", v.shape)
print("The shape of matrix x is ", x.shape)
x = v.reshape(4,1)
print("The shape of matrix x is ", x.shape)
x = v[None, :]
print("The shape of matrix x is ", x.shape)
x = v[:, None]
print("The shape of matrix x is ", x.shape)

The shape of vector v is  (4,)
The shape of matrix x is  (1, 4)
The shape of matrix x is  (4, 1)
The shape of matrix x is  (1, 4)
The shape of matrix x is  (4, 1)


##**NumPy Matrix Multiplication**

###**Element-wise Multiplication**

In [9]:
np.multiply(m, m)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

###**Matrix Product**

In [10]:
print("Matrix M \n",m,"\n\nMatrix N\n",m*2, "\n\nResultant Matrix\n",np.matmul(m, m*2))

Matrix M 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Matrix N
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

Resultant Matrix
 [[ 60  72  84]
 [132 162 192]
 [204 252 300]]
